# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/colorchecker2cielab',
                'doc_host': 'https://fligt.github.io',
                'git_url': 'https://github.com/fligt/colorchecker2cielab',
                'lib_path': 'colorchecker2cielab'},
  'syms': {'colorchecker2cielab.core': {'colorchecker2cielab.core.foo': ('core.html#foo', 'colorchecker2cielab/core.py')}}}
