# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/colorchecker2cielab',
                'doc_host': 'https://fligt.github.io',
                'git_url': 'https://github.com/fligt/colorchecker2cielab',
                'lib_path': 'colorchecker2cielab'},
  'syms': { 'colorchecker2cielab.core': { 'colorchecker2cielab.core.foo': ( 'check-your-colorchecker.html#foo',
                                                                            'colorchecker2cielab/core.py')},
            'colorchecker2cielab.utils': { 'colorchecker2cielab.utils._extract_RGBs': ( 'how-it-works.html#_extract_rgbs',
                                                                                        'colorchecker2cielab/utils.py'),
                                           'colorchecker2cielab.utils._interpoints': ( 'how-it-works.html#_interpoints',
                                                                                       'colorchecker2cielab/utils.py'),
                                           'colorchecker2cielab.utils._make_rectangles': ( 'how-it-works.html#_make_rectangles',
                                                                                           'colorchecker2cielab/utils.py'),
                                           'colorchecker2cielab.utils._plot': ('how-it-works.html#_plot', 'colorchecker2cielab/utils.py'),
                                           'colorchecker2cielab.utils.extract_color_patches': ( 'how-it-works.html#extract_color_patches',
                                                                                                'colorchecker2cielab/utils.py')}}}
