# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/05_color-management-report.ipynb.

# %% auto 0
__all__ = ['cielab_extractor']

# %% ../notebooks/05_color-management-report.ipynb 6
from . import extract_color_patches, RGBs_to_LABs 
import pandas as pd 
import re 

# %% ../notebooks/05_color-management-report.ipynb 7
def cielab_extractor(tif_file, write_excel=True):
    '''Extract RGB values from color patches and convert to CIELAB values table. '''  

    rectangles, RGBs = extract_color_patches(tif_file, make_plot=False) 
    LABs = RGBs_to_LABs(RGBs)

    if write_excel: 
        xlsx_file = re.sub('\.tif$', '_CIELABs.xlsx', tif_file, flags=re.IGNORECASE)
        print(f'Writing Colorchecker CIELAB values to excel file: \n"{xlsx_file}"\n')
        LABs.to_excel(xlsx_file)
    
    return LABs   
